export const SUBMIT_LOGIN_STARTED = "SUBMIT_LOGIN_STARTED";
export const SUBMIT_LOGIN_SUCCEEDED = "SUBMIT_LOGIN_SUCCEEDED";
export const SUBMIT_LOGIN_FAILED = "SUBMIT_LOGIN_FAILED";

export const SUBMIT_REGISTER_STARTED = "SUBMIT_REGISTER_STARTED";
export const SUBMIT_REGISTER_SUCCEEDED = "SUBMIT_REGISTER_SUCCEEDED";
export const SUBMIT_REGISTER_FAILED = "SUBMIT_REGISTER_FAILED";

export const SET_NEW_PASSWORD_STARTED = "SET_NEW_PASSWORD_STARTED";
export const SET_NEW_PASSWORD_SUCCEEDED = "SET_NEW_PASSWORD_SUCCEEDED";
export const SET_NEW_PASSWORD_FAILED = "SET_NEW_PASSWORD_FAILED";

export const FORGOT_PASSWORD_STARTED = "FORGOT_PASSWORD_STARTED";
export const FORGOT_PASSWORD_SUCCEEDED = "FORGOT_PASSWORD_SUCCEEDED";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";

export const GET_USER_STARTED = "GET_USER_STARTED";
export const GET_USER_SUCCEEDED = "GET_USER_SUCCEEDED";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const UPLOAD_IMAGE_STARTED = "UPLOAD_IMAGE_STARTED";
export const UPLOAD_IMAGE_SUCCEEDED = "UPLOAD_IMAGE_SUCCEEDED";
export const UPLOAD_IMAGE_FAILED = "UPLOAD_IMAGE_FAILED";

export const UPDATE_PROFILE_STARTED = "UPDATE_PROFILE_STARTED";
export const UPDATE_PROFILE_SUCCEEDED = "UPDATE_PROFILE_SUCCEEDED";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

//social networks
export const SOCIAL_NETWORKS_STARTED = "SOCIAL_NETWORKS_STARTED";
export const SOCIAL_NETWORKS_SUCCEEDED = "SOCIAL_NETWORKS_SUCCEEDED";
export const SOCIAL_NETWORKS_FAILED = "SOCIAL_NETWORKS_FAILED";

export const DISCONNECT_NETWORK_STARTED = "DISCONNECT_NETWORK_STARTED";
export const DISCONNECT_NETWORK_SUCCEEDED = "DISCONNECT_NETWORK_SUCCEEDED";
export const DISCONNECT_NETWORK_FAILED = "DISCONNECT_NETWORK_FAILED";
