export const SUBMIT_LOGIN_STARTED = "SUBMIT_LOGIN_STARTED";
export const SUBMIT_LOGIN_SUCCEEDED = "SUBMIT_LOGIN_SUCCEEDED";
export const SUBMIT_LOGIN_FAILED = "SUBMIT_LOGIN_FAILED";

//register
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

//resetEmail
export const RESET_EMAIL = "RESET_EMAIL";
export const RESET_EMAIL_SUCCESS = "RESET_EMAIL_SUCCESS";
export const RESET_EMAIL_REQUEST = "RESET_EMAIL_REQUEST";
export const RESET_EMAIL_FAILURE = "RESET_EMAIL_FAILURE";

//resetPassword
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
