export const SUBMIT_LOGIN_STARTED = "SUBMIT_LOGIN_STARTED";
export const SUBMIT_LOGIN_SUCCEEDED = "SUBMIT_LOGIN_SUCCEEDED";
export const SUBMIT_LOGIN_FAILED = "SUBMIT_LOGIN_FAILED";

//social networks
export const SOCIAL_NETWORKS_STARTED = "SOCIAL_NETWORKS_STARTED";
export const SOCIAL_NETWORKS_SUCCEEDED = "SOCIAL_NETWORKS_SUCCEEDED";
export const SOCIAL_NETWORKS_FAILED = "SOCIAL_NETWORKS_FAILED";
