export { DeleteAccount } from "./account";
export { ForgotPassword } from "./forgot-password";
export { Login } from "./login";
export { OnBoardingSkeleton } from "./on-boarding-skeleton";
export { UserInfo, UserProfile, EditProfile } from "./profile";
export { Register } from "./register";
export { ResetEmail } from "./reset-email";
export { ResetPassword } from "./reset-password";
export { Verification } from "./verification";
export { About } from "./about";
export { Privacy } from "./privacy";
export { Information } from "./information";
